/*
 * Can use:
 * new Mongo(<host:port>)
 * 
 * to populate the DB remotely
 */

conn = new Mongo();
db = conn.getDB("test"); // Update here to populate a different db

db.getCollections("locations").updateMany({}, locations, upsert = true);

var locations =[
    {     "Acute Care Unit": "2211 Wesbrook Mall"                                      },          
    {     "Anthropology and Sociology": "6303 North West Marine Drive"                 },
    {     "Aquatic Ecosystems Research Laboratory": "2202 Main Mall"                   },
    {     "Asian Centre": "1871 West Mall"                                             },
    {     "Auditorium": "1924 West Mall"                                               },
    {     "Auditorium Annex": "1924 West Mall"                                         },
    {     "B.C. Binnings Studio": "6373 University Boulevard"                          },
    {     "Biological Sciences": "6270 University Boulevard"                           },
    {     "Brock Hall Annex": "1874 East Mall"                                         }, 
    {     "Buchanan": "1866 Main Mall"                                                 }, 
    {     "Buchanan Tower": "1873 East Mall"                                           },
    {     "Chan Centre": "6265 Crescent Road"                                          }, 
    {     "Chemical and Biological Engineering Building": "2360 East Mall V6T 1Z3"     },
    {     "Chemical Engineering": "2216 Main Mall"                                     },
    {     "Chemistry": "2036 Main Mall"                                                },
    {     "Civil and Mechanical Engineering": "6250 Applied Science Lane"              },
    {     "D.H. Copp": "2146 Health Sciences Mall"                                     },
    {     "David Lam Management Research Centre": "2033 Main Mall V6T 1Z2"             },
    {     "Dorothy Somerset Studio": "6361 University Blvd"                            }, 
    {     "Douglas Kenny": "2136 West Mall"                                            },
    {     "Earth and Ocean Sciences - East": "2219 Main Mall"                          },
    {     "Earth and Ocean Sciences - Main": "6339 Stores Road"                        },
    {     "Food, Nutrition and Health": "2205 East Mall"                               },
    {     "Forest Sciences Centre": "2424 Main Mall"                                   }, 
    {     "Frank Forward": "6350 Stores Road"                                          },
    {     "Frederic Lasserre": "6333 Memorial Road"                                    },
    {     "Frederic Wood Theatre": "6354 Crescent Road"                                },
    {     "Friedman Building": "2177 Wesbrook Mall V6T 1Z3"                            },
    {     "Geography": "1984 West Mall"                                                },
    {     "George Cunningham": "2146 East Mall"                                        },
    {     "Hebb": "2045 East Mall"                                                     },
    {     "Hennings": "6224 Agricultural Road"                                         },
    {     "Henry Angus": "2053 Main Mall"                                              }, 
    {     "Hugh Dempster Pavilion": "6245 Agronomy Road V6T 1Z4"                       },
    {     "Hut M-22": "2109 West Mall"                                                 },
    {     "Institute for Computing (ICICS/CS)": "2366 Main Mall"                       },
    {     "Irving K Barber Learning Centre": "1961 East Mall V6T 1Z1"                  },
    {     "J.B. MacDonald": "2199 West Mall"                                           },
    {     "Jack Bell Building for the School of Social Work": "2080 West Mall"         },
    {     "James Mather": "5804 Fairview Avenue"                                       },
    {     "Landscape Architecture Annex": "2371 Main Mall"                             },
    {     "Law (Curtis Building)": "1822 East Mall"                                    },
    {     "Leonard S. Klinck (also known as CSCI)": "6356 Agricultural Road"           },
    {     "Library Processing Centre": "2206 East Mall"                                },
    {     "Life Sciences Centre": "2350 Health Sciences Mall"                          },
    {     "MacLeod": "2356 Main Mall"                                                  },
    {     "MacMillan": "2357 Main Mall"                                                },
    {     "Math/Stats Resource Centre": "6368 Agricultural Road"                       },
    {     "Mathematics": "1984 Mathematics Road"                                       },
    {     "Mathematics Annex": "1986 Mathematics Road"                                 },
    {     "Medical Sciences Block C": "2176 Health Sciences Mall"                      },
    {     "Michael Smith Laboratories": "2185 East Mall"                               },
    {     "Music": "6361 Memorial Road"                                                },
    {     "Neville Scarfe": "2125 Main Mall"                                           },
    {     "Ponderosa Annex E": "2034 Lower Mall"                                       },
    {     "Ponderosa Office Annex F": "2008 Lower Mall"                                },
    {     "Ponderosa Office Annex H": "2008 Lower Mall"                                },
    {     "Robert F. Osborne Centre": "6108 Thunderbird Boulevard"                     },
    {     "Student Recreation Centre": "6000 Student Union Blvd"                       },
    {     "The Leon and Thea Koerner University Centre": "6331 Crescent Road V6T 1Z1"  },
    {     "Theatre-Film Production Building": "6358 University Blvd, V6T 1Z4"          },
    {     "Theatre-Film Production Building Annex": "6358 University Blvd, V6T 1Z4"    },
    {     "War Memorial Gymnasium": "6081 University Blvd"                             },
    {     "Wesbrook": "6174 University Boulevard"                                      },
    {     "West Mall Annex": "1933 West Mall"                                          },  
    {     "West Mall Swing Space": "2175 West Mall V6T 1Z4"                            },
    {     "Woodward (Instructional Resources Centre-IRC)": "2194 Health Sciences Mall" } 
];